import { alpha, createTheme } from '@mui/material';

const whiteBase = '#ffffff';
const blackBase = '#161616';
const backdropBase = '151515';
const accentGreenBase = '#bedbB0';
const accentVioletBase = '#5255bc';
const accentGreenHoverBase = '#9dc888';
const accentVioletHoverBase = '#7b7ede';

export const authColors = {
  background: `linear-gradient(180deg, rgba(196, 196, 196, 0.00) 25%, ${accentGreenBase} 92.19%)`,
  buttonBackground: blackBase,
  textPrimary: blackBase,
  textSecondary: whiteBase,
  textSecondaryDark: alpha(whiteBase, 0.3),
};

const darkTheme = createTheme({
  palette: {
    background: {
      primary: '#1f1f1f',
      modal: backdropBase,
      backdrop: alpha(backdropBase, 0.5),
      activeBoardItem: '#1f1f1f',
      support: '#1f1f1f',
      calendar: '#1f1f1f',
      sidebar: '#121212',
      card: '#121212',
      verticalScrollbarGutter: alpha(whiteBase, 0.08),
      horisontalScrollbarGutter: blackBase,
      verticalScrollbarSlider: '#121212',
      horisontalScrollbarSlider: alpha(whiteBase, 0.1),
      avatarDefault: backdropBase,
      buttonPlus: backdropBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusSideBar: accentGreenBase,
      buttonPlusHoverSideBar: accentGreenHoverBase,
      header: blackBase,
      columnTitleBlock: blackBase,
    },
    text: {
      primary: whiteBase,
      dark: alpha(whiteBase, 0.2),
      medium: alpha(whiteBase, 0.5),
      light: alpha(whiteBase, 0.8),
      sidebarPrimary: whiteBase,
      activeBoardItem: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      passiveBoardItem: alpha(whiteBase, 0.5),
      themeMenuItems: alpha(whiteBase, 0.5),
      cardDescription: alpha(whiteBase, 0.8),
      homeDefault: alpha(whiteBase, 0.8),
      primaryButton: blackBase,
      activeDay: '#1f1f1f',
    },
    icon: {
      main: whiteBase,
      mainAlpha: alpha(whiteBase, 0.5),
      medium: alpha(whiteBase, 0.5),
      light: alpha(whiteBase, 0.8),
      activeSideBar: whiteBase,
      passiveSideBar: alpha(whiteBase, 0.5),
      signOut: accentGreenBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: '#121212',
      buttonPlusAvatar: blackBase,
      buttonPlusSideBar: '#121212',
    },
    accent: {
      main: accentGreenBase,
      hover: accentGreenHoverBase,
    },
  },
});
const lightTheme = createTheme({
  palette: {
    background: {
      primary: '#f6f6f7',
      modal: '#fcfcfc',
      backdrop: alpha(backdropBase, 0.3),
      activeBoardItem: '#f6f6f7',
      support: '#f6f6f7',
      calendar: whiteBase,
      sidebar: whiteBase,
      card: whiteBase,
      verticalScrollbarGutter: '#e8e8e8',
      horisontalScrollbarGutter: whiteBase,
      verticalScrollbarSlider: alpha(blackBase, 0.1),
      horisontalScrollbarSlider: '#e8e8e8',
      avatarDefault: whiteBase,
      buttonPlus: blackBase,
      buttonPlusSecondary: blackBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusSideBar: accentGreenBase,
      buttonPlusHoverSideBar: accentGreenHoverBase,
      header: 'fcfcfc',
      columnTitleBlock: whiteBase,
    },
    text: {
      primary: blackBase,
      dark: alpha(blackBase, 0.8),
      medium: alpha(blackBase, 0.5),
      light: alpha(blackBase, 0.2),
      sidebarPrimary: blackBase,
      activeBoardItem: blackBase,
      sidebarSecondary: alpha(blackBase, 0.5),
      passiveBoardItem: alpha(blackBase, 0.5),
      themeMenuItems: blackBase,
      cardDescription: alpha(blackBase, 0.7),
      homeDefault: alpha(blackBase, 0.7),
      primaryButton: blackBase,
      activeDay: blackBase,
    },
    icon: {
      main: blackBase,
      mainAlpha: alpha(blackBase, 0.5),
      medium: alpha(blackBase, 0.5),
      light: alpha(blackBase, 0.8),
      activeSideBar: blackBase,
      passiveSideBar: alpha(blackBase, 0.5),
      signOut: accentGreenBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusAvatar: blackBase,
      buttonPlusSideBar: '#121212',
    },
    accent: {
      main: accentGreenBase,
      hover: accentGreenHoverBase,
    },
  },
});
const violetTheme = createTheme({
  palette: {
    background: {
      primary: '#ecedfd',
      modal: '#fcfcfc',
      backdrop: alpha(backdropBase, 0.3),
      activeBoardItem: alpha(whiteBase, 0.5),
      support: '#ecedfd66',
      calendar: whiteBase,
      sidebar: accentVioletBase,
      card: whiteBase,
      verticalScrollbarGutter: whiteBase,
      horisontalScrollbarGutter: whiteBase,
      verticalScrollbarSlider: '#b8bcfd',
      horisontalScrollbarSlider: '#b8bcfd',
      avatarDefault: whiteBase,
      buttonPlus: whiteBase,
      buttonPlusSecondary: accentVioletBase,
      buttonPlusAvatar: '#ecedfd',
      buttonPlusSideBar: '#b8bcfd',
      buttonPlusHoverSideBar: '#979cea',
      header: whiteBase,
      columnTitleBlock: blackBase,
    },
    text: {
      primary: blackBase,
      dark: alpha(blackBase, 0.8),
      medium: alpha(blackBase, 0.5),
      light: alpha(blackBase, 0.2),
      sidebarPrimary: whiteBase,
      activeBoardItem: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      passiveBoardItem: alpha(whiteBase, 0.5),
      themeMenuItems: blackBase,
      cardDescription: alpha(blackBase, 0.7),
      homeDefault: alpha(blackBase, 0.7),
      primaryButton: whiteBase,
      activeDay: '#fcfcfc',
    },
    icon: {
      main: blackBase,
      mainAlpha: alpha(blackBase, 0.5),
      medium: alpha(blackBase, 0.5),
      light: alpha(blackBase, 0.8),
      activeSideBar: whiteBase,
      passiveSideBar: alpha(whiteBase, 0.5),
      signOut: whiteBase,
      buttonPlusPrimary: blackBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusAvatar: blackBase,
      buttonPlusSideBar: whiteBase,
    },
    accent: {
      main: accentVioletBase,
      hover: accentVioletHoverBase,
    },
  },
});

export { darkTheme, lightTheme, violetTheme };
