import { alpha, createTheme } from '@mui/material';

import { baseColors, breakpoints } from 'constants';

const {
  whiteBase,
  blackBase,
  backdropBase,
  accentGreenBase,
  accentVioletBase,
  accentGreenHoverBase,
  accentVioletHoverBase,
} = baseColors.generalColors;

const darkTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: '#1f1f1f',
      avatarDefault: backdropBase,
      backdrop: alpha(backdropBase, 0.5),
      buttonPlus: blackBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusHoverSideBar: accentGreenHoverBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: accentGreenBase,
      calendar: '#1f1f1f',
      card: '#121212',
      columnTitleBlock: blackBase,
      header: blackBase,
      horisontalScrollbarGutter: blackBase,
      horisontalScrollbarSlider: alpha(whiteBase, 0.1),
      input: '#1f1f1f',
      lineBefore: alpha(whiteBase, 0.1),
      modal: backdropBase,
      modalBorder: alpha(accentGreenBase, 0.5),
      primary: '#1f1f1f',
      sidebar: '#121212',
      support: '#1f1f1f',
      verticalScrollbarGutter: alpha(whiteBase, 0.08),
      verticalScrollbarSlider: '#121212',
      withoutPriorityBackground: alpha(whiteBase, 0.3),
    },
    text: {
      activeBoardItem: whiteBase,
      activeDay: '#1f1f1f',
      cardDescription: alpha(whiteBase, 0.5),
      homeDefault: alpha(whiteBase, 0.5),
      passiveBoardItem: alpha(whiteBase, 0.5),
      primary: whiteBase,
      primaryDark: alpha(whiteBase, 0.2),
      primaryLight: alpha(whiteBase, 0.8),
      primaryMedium: alpha(whiteBase, 0.5),
      primaryButton: blackBase,
      shadowColor: whiteBase,
      sidebarPrimary: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      themeMenuItems: alpha(whiteBase, 0.5),
    },
    icon: {
      activeSideBar: whiteBase,
      attention: '#df1010',
      attentionHover: '#ef4444',
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: '#121212',
      buttonPlusSideBar: '#121212',
      passiveSideBar: alpha(whiteBase, 0.5),
      primary: whiteBase,
      primaryExtraLight: alpha(whiteBase, 0.1),
      primaryLight: alpha(whiteBase, 0.8),
      primaryMedium: alpha(whiteBase, 0.5),
      signOut: accentGreenBase,
      signOutHover: accentGreenHoverBase,
    },
    accent: {
      main: accentGreenBase,
      light: accentGreenHoverBase,
    },
  },
  breakpoints,
});
const lightTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: '#f6f6f7',
      avatarDefault: whiteBase,
      backdrop: alpha(backdropBase, 0.3),
      buttonPlus: blackBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusHoverSideBar: accentGreenHoverBase,
      buttonPlusSecondary: blackBase,
      buttonPlusSideBar: accentGreenBase,
      calendar: whiteBase,
      card: whiteBase,
      columnTitleBlock: whiteBase,
      header: 'fcfcfc',
      horisontalScrollbarGutter: whiteBase,
      horisontalScrollbarSlider: '#e8e8e8',
      input: '#fcfcfc',
      lineBefore: alpha(blackBase, 0.1),
      modal: '#fcfcfc',
      modalBorder: alpha(accentGreenBase, 0.5),
      primary: '#f6f6f7',
      sidebar: whiteBase,
      support: '#f6f6f7',
      verticalScrollbarGutter: '#e8e8e8',
      verticalScrollbarSlider: alpha(blackBase, 0.1),
      withoutPriorityBackground: alpha(blackBase, 0.3),
    },
    text: {
      activeBoardItem: blackBase,
      activeDay: blackBase,
      cardDescription: alpha(blackBase, 0.7),
      homeDefault: alpha(blackBase, 0.7),
      passiveBoardItem: alpha(blackBase, 0.5),
      primary: blackBase,
      primaryDark: alpha(blackBase, 0.2),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      primaryButton: blackBase,
      shadowColor: whiteBase,
      sidebarPrimary: blackBase,
      sidebarSecondary: alpha(blackBase, 0.5),
      themeMenuItems: blackBase,
    },
    icon: {
      activeSideBar: blackBase,
      attention: '#df1010',
      attentionHover: '#ef4444',
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: '#121212',
      passiveSideBar: alpha(blackBase, 0.5),
      primary: blackBase,
      primaryExtraLight: alpha(blackBase, 0.1),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      signOut: accentGreenBase,
      signOutHover: accentGreenHoverBase,
    },
    accent: {
      main: accentGreenBase,
      light: accentGreenHoverBase,
    },
  },
  breakpoints,
});
const violetTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: alpha(whiteBase, 0.5),
      avatarDefault: whiteBase,
      backdrop: alpha(backdropBase, 0.3),
      buttonPlus: whiteBase,
      buttonPlusAvatar: '#ecedfd',
      buttonPlusHoverSideBar: '#979cea',
      buttonPlusSecondary: accentVioletBase,
      buttonPlusSideBar: '#b8bcfd',
      calendar: whiteBase,
      card: whiteBase,
      columnTitleBlock: blackBase,
      header: whiteBase,
      horisontalScrollbarGutter: whiteBase,
      horisontalScrollbarSlider: '#b8bcfd',
      input: '#fcfcfc',
      lineBefore: alpha(blackBase, 0.1),
      modal: '#fcfcfc',
      modalBorder: alpha(accentVioletBase, 0.5),
      primary: '#ecedfd',
      sidebar: accentVioletBase,
      support: '#ecedfd66',
      verticalScrollbarGutter: whiteBase,
      verticalScrollbarSlider: '#b8bcfd',
      withoutPriorityBackground: alpha(blackBase, 0.3),
    },
    text: {
      activeBoardItem: whiteBase,
      activeDay: '#fcfcfc',
      cardDescription: alpha(blackBase, 0.7),
      homeDefault: alpha(blackBase, 0.7),
      passiveBoardItem: alpha(whiteBase, 0.5),
      primary: blackBase,
      primaryDark: alpha(blackBase, 0.2),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      primaryButton: whiteBase,
      shadowColor: whiteBase,
      sidebarPrimary: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      themeMenuItems: blackBase,
    },
    icon: {
      activeSideBar: whiteBase,
      attention: '#df1010',
      attentionHover: '#ef4444',
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: blackBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: whiteBase,
      passiveSideBar: alpha(whiteBase, 0.5),
      primary: blackBase,
      primaryExtraLight: alpha(blackBase, 0.1),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      signOut: whiteBase,
      signOutHover: '#b8bcfd',
    },
    accent: {
      main: accentVioletBase,
      light: accentVioletHoverBase,
    },
  },
  breakpoints,
});

const themes = {
  darkTheme,
  lightTheme,
  violetTheme,
};

export default themes;
