import { alpha, createTheme } from '@mui/material';

import { BASE_COLORS, BREAKPOINTS as breakpoints } from 'constants';

const {
  whiteBase,
  blackBase,
  backdropBase,
  backgroundDarkBase,
  foregroundDarkBase,
  backgroundLightBase,
  foregroundLightBase,
  backgroundVioletBase,
  scrollBarLightBase,
  scrollBarVioletBase,
  accentGreenBase,
  accentVioletBase,
  accentGreenHoverBase,
  accentVioletHoverBase,
  attentionBase,
  attentionHoverBase,
} = BASE_COLORS.generalColors;

const darkTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: backgroundDarkBase,
      avatarDefault: backdropBase,
      backdrop: alpha(backdropBase, 0.5),
      buttonPlus: blackBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: accentGreenBase,
      calendar: backgroundDarkBase,
      card: foregroundDarkBase,
      createBoardBorder: alpha(whiteBase, 0.1),
      header: blackBase,
      horisontalScrollbarGutter: blackBase,
      horisontalScrollbarSlider: alpha(whiteBase, 0.1),
      input: backgroundDarkBase,
      lineBefore: alpha(whiteBase, 0.1),
      modal: backdropBase,
      modalBorder: alpha(accentGreenBase, 0.5),
      primary: backgroundDarkBase,
      sidebar: foregroundDarkBase,
      support: backgroundDarkBase,
      verticalScrollbarGutter: alpha(whiteBase, 0.08),
      verticalScrollbarSlider: foregroundDarkBase,
      withoutPriorityBackground: alpha(whiteBase, 0.3),
    },
    text: {
      activeDay: backgroundDarkBase,
      attention: attentionBase,
      primary: whiteBase,
      primaryDark: alpha(whiteBase, 0.2),
      primaryLight: alpha(whiteBase, 0.8),
      primaryMedium: alpha(whiteBase, 0.5),
      primaryButton: blackBase,
      secondary: alpha(whiteBase, 0.5),
      shadowColor: whiteBase,
      sidebarPrimary: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      themeMenuItems: alpha(whiteBase, 0.5),
    },
    icon: {
      activeSideBar: whiteBase,
      attention: attentionBase,
      attentionHover: attentionHoverBase,
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: foregroundDarkBase,
      buttonPlusSideBar: foregroundDarkBase,
      passiveSideBar: alpha(whiteBase, 0.5),
      primary: whiteBase,
      primaryExtraLight: alpha(whiteBase, 0.1),
      primaryLight: alpha(whiteBase, 0.8),
      primaryMedium: alpha(whiteBase, 0.5),
      signOut: accentGreenBase,
      signOutHover: accentGreenHoverBase,
    },
    accent: {
      main: accentGreenBase,
      light: accentGreenHoverBase,
    },
  },
  breakpoints,
});
const lightTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: backgroundLightBase,
      avatarDefault: whiteBase,
      backdrop: alpha(backdropBase, 0.3),
      buttonPlus: blackBase,
      buttonPlusAvatar: accentGreenBase,
      buttonPlusSecondary: blackBase,
      buttonPlusSideBar: accentGreenBase,
      calendar: whiteBase,
      card: whiteBase,
      createBoardBorder: alpha(blackBase, 0.1),
      header: foregroundLightBase,
      horisontalScrollbarGutter: whiteBase,
      horisontalScrollbarSlider: scrollBarLightBase,
      input: foregroundLightBase,
      lineBefore: alpha(blackBase, 0.1),
      modal: foregroundLightBase,
      modalBorder: alpha(accentGreenBase, 0.5),
      primary: backgroundLightBase,
      sidebar: whiteBase,
      support: backgroundLightBase,
      verticalScrollbarGutter: scrollBarLightBase,
      verticalScrollbarSlider: alpha(blackBase, 0.1),
      withoutPriorityBackground: alpha(blackBase, 0.3),
    },
    text: {
      activeDay: blackBase,
      attention: attentionBase,
      primary: blackBase,
      primaryDark: alpha(blackBase, 0.2),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      primaryButton: blackBase,
      secondary: alpha(blackBase, 0.7),
      shadowColor: whiteBase,
      sidebarPrimary: blackBase,
      sidebarSecondary: alpha(blackBase, 0.5),
      themeMenuItems: blackBase,
    },
    icon: {
      activeSideBar: blackBase,
      attention: attentionBase,
      attentionHover: attentionHoverBase,
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: whiteBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: foregroundDarkBase,
      passiveSideBar: alpha(blackBase, 0.5),
      primary: blackBase,
      primaryExtraLight: alpha(blackBase, 0.1),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      signOut: accentGreenBase,
      signOutHover: accentGreenHoverBase,
    },
    accent: {
      main: accentGreenBase,
      light: accentGreenHoverBase,
    },
  },
  breakpoints,
});
const violetTheme = createTheme({
  palette: {
    background: {
      activeBoardItem: alpha(whiteBase, 0.5),
      avatarDefault: whiteBase,
      backdrop: alpha(backdropBase, 0.3),
      buttonPlus: whiteBase,
      buttonPlusAvatar: backgroundVioletBase,
      buttonPlusSecondary: accentVioletBase,
      buttonPlusSideBar: scrollBarVioletBase,
      calendar: whiteBase,
      card: whiteBase,
      createBoardBorder: alpha(whiteBase, 0.1),
      header: whiteBase,
      horisontalScrollbarGutter: whiteBase,
      horisontalScrollbarSlider: scrollBarVioletBase,
      input: foregroundLightBase,
      lineBefore: alpha(blackBase, 0.1),
      modal: foregroundLightBase,
      modalBorder: alpha(accentVioletBase, 0.5),
      primary: backgroundVioletBase,
      sidebar: accentVioletBase,
      support: alpha(backgroundVioletBase, 0.4),
      verticalScrollbarGutter: whiteBase,
      verticalScrollbarSlider: scrollBarVioletBase,
      withoutPriorityBackground: alpha(blackBase, 0.3),
    },
    text: {
      activeDay: foregroundLightBase,
      attention: attentionBase,
      primary: blackBase,
      primaryDark: alpha(blackBase, 0.2),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      primaryButton: whiteBase,
      secondary: alpha(blackBase, 0.7),
      shadowColor: whiteBase,
      sidebarPrimary: whiteBase,
      sidebarSecondary: alpha(whiteBase, 0.5),
      themeMenuItems: blackBase,
    },
    icon: {
      activeSideBar: whiteBase,
      attention: attentionBase,
      attentionHover: attentionHoverBase,
      buttonPlusAvatar: blackBase,
      buttonPlusPrimary: blackBase,
      buttonPlusSecondary: whiteBase,
      buttonPlusSideBar: whiteBase,
      passiveSideBar: alpha(whiteBase, 0.5),
      primary: blackBase,
      primaryExtraLight: alpha(blackBase, 0.1),
      primaryLight: alpha(blackBase, 0.8),
      primaryMedium: alpha(blackBase, 0.5),
      signOut: whiteBase,
      signOutHover: scrollBarVioletBase,
    },
    accent: {
      main: accentVioletBase,
      light: accentVioletHoverBase,
    },
  },
  breakpoints,
});

const themes = {
  darkTheme,
  lightTheme,
  violetTheme,
};

export default themes;
